version: "3.7"

services:
  db:
    image: postgres:15
    hostname: linebot_postgres
    container_name: linebot_postgres
    restart: always
    environment:
      POSTGRES_DB: linebot_db
      POSTGRES_USER: linebot_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linebot_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true # Keeps the container running for debugging
    networks:
      - backend_network
networks:
  backend_network:
    name: backend_network
    driver: bridge
